geral/urls.py
# -*- coding: utf-8

from django.conf.urls import url
from geral import views
from django.views.generic import TemplateView

urlpatterns = (
    url(r'^$', TemplateView.as_view(template_name="geral/index.html"), name='index'),
    url(r'accounts/register/$', views.ContadorCreateView.as_view(), name='user-create'),
    url(r'minha-conta$', views.LancamentoListView.as_view(), name='lancamento-list'),
    url(r'submeter-comprovante$', views.LancamentoCreateView.as_view(), name='lancamento-create'),
    url(r'meus-planos$', views.PlanoListView.as_view(), name='plano-list'),
    url(r'incluir-planos$', views.PlanoCreateView.as_view(), name='plano-create'),
)

sistema_tesouraria/urls.py
from django.conf.urls import url
from django.contrib import admin
#from django.contrib.auth import views as auth_views
from django.conf.urls import include
from django.views.generic.base import RedirectView
from django.contrib.auth import views as auth_views
from django.contrib.auth.views import login, logout

from geral.views import PasswordResetViewSendgrid

urlpatterns = [
    url(r'^admin/', RedirectView.as_view(url='https://www.youtube.com/watch?v=ednKK8GlvwI')),
    url(r'^conselho/', admin.site.urls),
    url(r'^signup/', include('confirmation.urls')),
    url(r'^accounts/login/$', login, name='login'),
    url(r'^accounts/logout/$', logout, name='logout'),
    url(r'^', include('geral.urls')),

    # Password Reset
    url(r'^password_reset/$', PasswordResetViewSendgrid.as_view(), name='password_reset'),
    url(r'^', include('django.contrib.auth.urls')),

    # Serve Database Files directly
    url(r'', include('database_files.urls')),
]

from django.conf import settings
from django.conf.urls.static import static

# BAD - TODO: Refactor
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

geral/models.py
from django.db import models
from django.utils import timezone

from django.contrib.auth.models import User
from imagekit.models import ImageSpecField
from imagekit.processors import ResizeToFill
from django.db.models.signals import post_save
from simple_history.models import HistoricalRecords

from geral.mail_shortcuts import sendgrid_lancamento
from geral.mail_shortcuts import sendgrid_alert_admin


class Associado(models.Model):

    user = models.OneToOneField(
            User,
            on_delete=models.CASCADE,
            related_name="associado",
            null=True, blank=True)

    ativo = models.BooleanField(default=True)
    last_modified = models.DateTimeField(auto_now=True)

    # Foto
    avatar = models.ImageField(upload_to='fotos', blank=True, null=True)

    avatar_profile = ImageSpecField(source='avatar',
                                    processors=[ResizeToFill(170, 170)],
                                    format='JPEG',
                                    options={'quality': 90})

    avatar_thumbnail = ImageSpecField(source='avatar',
                                      processors=[ResizeToFill(60, 60)],
                                      format='JPEG',
                                      options={'quality': 80})

    telefone = models.CharField(max_length=32)
    cpf = models.CharField(max_length=32)
    enderço = models.CharField(max_length=128)
    contato_emergencia = models.CharField(max_length=128)
    mestre = models.CharField(max_length=32)

    def __str__(self):
        return self.user.__str__()

    def plano_qs(self, planos_list=[]):
        planos = Plano.objects.filter(user=self.user).order_by('-id')
        if planos_list:
            planos = planos.filter(plano__in=planos_list)
        return planos

    def is_in_starving_hacker(self):
        qs = self.plano_qs(['sh'])
        return [p for p in qs if p.state in ('v',)]

    def is_in_anuidade(self):
        qs = self.plano_qs(['an'])
        return [p for p in qs if p.state in ('v',)]

    def has_mensalidade(self):
        qs = self.plano_qs(['ml', 'pp'])
        return [p for p in qs if p.state in ('v',)]

    def get_plano_vigente(self):
       anuidade = self.is_in_anuidade()
       starving_hacker = self.is_in_starving_hacker()
       plano_vigente = self.has_mensalidade()

       if anuidade:
           return anuidade[0]
       elif starving_hacker:
           return starving_hacker[0]
       elif plano_vigente:
           return plano_vigente[0]

       return False

def create_user_associado(sender, instance, created, **kwargs):

    if kwargs.get('raw', False):
        # https://code.djangoproject.com/ticket/17880
        return

    if created:
        try:
            if instance.associado is not None:
                pass
        except User.associado.RelatedObjectDoesNotExist:
            Associado.objects.create(user=instance)

            Plano.objects.create(
                    moderation_status = 'A',
                    approved_timestamp=timezone.now(),
                    user=instance,
                    plano='ml',
                    validade_data_inicio = timezone.now().date(),
                    descricao = "Plano padrão.",
                    valor = 105.00)

            Lancamento.objects.create(
                    moderation_status = 'A',
                    approved_timestamp=timezone.now(),
                    user=instance,
                    autor='s',
                    valor='0',
                    saldo='0',
                    timestamp_comprovante=timezone.now(),
                    credito_debito='c',
                    descricao='Abertura da Conta')

post_save.connect(create_user_associado, sender=User)


class ModeratedModel(models.Model):
    """
        DOCS: TODO
    """
    APPROVED = 'A'
    REJECTED = 'R'
    PENDING = 'P'

    MODERATION_CHOICES = (
        (APPROVED, 'Approved'),
        (REJECTED, 'Rejected'),
        (PENDING, 'Pending'),
    )

    class Meta:
        abstract = True

    history = HistoricalRecords(inherit=True)

    created_on = models.DateTimeField(auto_now_add=True)
    last_modified = models.DateTimeField(auto_now=True)

    approved_timestamp = models.DateTimeField(blank=True, null=True)
    moderation_comments = models.TextField(blank=True, null=True)

    moderation_status = models.CharField(
        verbose_name='Status de Moderação',
        help_text='O status "Rejected" não permite que o registro seja mostrado.',
        max_length=1,
        choices=MODERATION_CHOICES,
        default=PENDING)


class Plano(ModeratedModel):

    PLANO_CHOICES = (
        ('an', 'Anuidade'),
        ('ml', 'Itaú - Mensalidades'),
        ('pp', 'Paypal - Mensalidades'),
        ('sh', 'Starving Hacker'),
    )

    PLANO_PRICES = {
        'an': 95*12,
        'ml': 105,
        'pp': 95,
        'sh': 0,
    }

    PLANO_STATE = {
        'p': 'pré-programado',
        'v': 'vigente',
        'e': 'encerrado',
    }


    # tipo plano (Anuidade, Starving)
    plano = models.CharField(
        max_length=2,
        choices=PLANO_CHOICES,
        default='ml'
    )

    # user
    user = models.ForeignKey(
        User,
        models.SET_NULL,
        blank=True,
        null=True,
    )

    validade_data_inicio = models.DateField(blank=True, null=True)
    data_validade_fim = models.DateField(blank=True, null=True)
    descricao = models.TextField()
    valor = models.DecimalField(max_digits=15, decimal_places=2)

    def __str__(self):
        validade = self.data_validade_fim if  self.data_validade_fim is not None else 'Indeterminado'
        return "%s - R$%d até %s" % (self.get_plano_display(), self.valor, validade)

    @property
    def state(self):
        ts = timezone.now().date()
        if self.validade_data_inicio >= ts:
            return 'p'
        if self.data_validade_fim is not None:
            if self.data_validade_fim <= ts:
                return 'e'
        return 'v'

    def save(self, *args, **kwargs):
        super(Plano, self).save(*args, **kwargs)
        sendgrid_alert_admin()
        print("Email Plano Enviado.")


class Lancamento(ModeratedModel):

    AUTHOR_CHOICES = (
        ('s', 'System'),
        ('a', 'Admin'),
        ('u', 'User'),
    )

    CREDITO_DEBITO_CHOICES = (
        ('d', 'Débito'),
        ('c', 'Crédito'),
        #('n', 'Doação'),
    )

    # user
    user = models.ForeignKey(
        User,
        models.SET_NULL,
        null=True,
    )

    # autor (sistema usuário)
    autor = models.CharField(
        max_length=1,
        choices=AUTHOR_CHOICES
    )
    # Credito ou debito
    credito_debito = models.CharField(
        max_length=1,
        choices=CREDITO_DEBITO_CHOICES
    )
    # data
    timestamp_comprovante = models.DateTimeField('Data do Comprovante')
    # valor
    valor = models.DecimalField(max_digits=15, decimal_places=2)
    # saldo
    saldo = models.DecimalField(
            max_digits=15, decimal_places=2,
            blank=True, null=True)
    # comprovante
    comprovante = models.FileField(
            upload_to='comprovantes/',
            blank=True, null=True)
    # descricao
    descricao = models.TextField()

    def __str__(self):
        valor = self.valor
        saldo = self.saldo if not self.saldo is None else 0.0
        id = self.id if not self.id is None else 0
        return "%d - %s: R$%.2f %s (R$%.2f)" % (id, self.user, valor, self.descricao, saldo)

    def save(self, *args, **kwargs):
        if self.moderation_status == 'A' and self.saldo is None:
            self.approved_timestamp = timezone.now()
            qs = Lancamento.objects.exclude(approved_timestamp__isnull=True)
            len(qs) # eval
            lancamento_obj = qs.filter(
                    user=self.user,
                    approved_timestamp__lt=self.approved_timestamp,
                    moderation_status='A').latest('approved_timestamp')

            valor = self.valor if self.credito_debito == 'c' else -self.valor
            novo_saldo = lancamento_obj.saldo + valor
            self.saldo = novo_saldo

        super(Lancamento, self).save(*args, **kwargs)

def alert_lancamento(sender, instance, created, **kwargs):
    # Nao manda msg se o usuario nao estiver confirmado
    if instance.user.is_active:
        sendgrid_lancamento(instance)
        print("Email Lançamento Enviado.")

post_save.connect(alert_lancamento, sender=Lancamento)

geral/views.py
# -*- coding: utf-8

import json
import requests

from django.shortcuts import redirect
from django.utils import timezone
from django.views.generic.list import ListView
from django.views.generic import CreateView

from django.contrib.auth.mixins import LoginRequiredMixin
from django.core.urlresolvers import reverse_lazy
from django.contrib.auth.models import User
from django.contrib.auth.views import PasswordResetView

from geral.models import Plano
from geral.models import Lancamento
from geral.form import UserForm
from geral.form import PasswordResetFormSendgrid


class PlanoListView(LoginRequiredMixin, ListView):

    model = Plano

    def get_queryset(self):
        return Plano.objects.filter(
                user=self.request.user
                ).order_by('approved_timestamp', 'id')


class LancamentoListView(LoginRequiredMixin, ListView):

    model = Lancamento

    def get_queryset(self):
        return Lancamento.objects.filter(
                user=self.request.user
                ).order_by('approved_timestamp', 'id')


class LancamentoCreateView(LoginRequiredMixin, CreateView):
    fields = ['valor', 'timestamp_comprovante', 'comprovante', 'descricao']
    model = Lancamento

    def form_valid(self, form):
        lancamento = form.save(commit=False)
        lancamento.autor = 'u'
        lancamento.user = self.request.user
        lancamento.credito_debito = 'c'
        lancamento.comprovante = self.request.FILES['comprovante']

        return super(LancamentoCreateView, self).form_valid(form)

    def get_success_url(self):
        return reverse_lazy('lancamento-list')


class PlanoCreateView(LoginRequiredMixin, CreateView):
    fields = ['plano']
    model = Plano

    def form_valid(self, form):
        obj = form.save(commit=False)
        obj.autor = 'u'
        obj.user = self.request.user
        obj.valor = Plano.PLANO_PRICES[obj.plano]

        return super(PlanoCreateView, self).form_valid(form)

    def get_success_url(self):
        return reverse_lazy('plano-list')



class ContadorCreateView(CreateView):
    model = User
    form_class = UserForm

    def form_valid(self, form):

        response = requests.post('https://www.google.com/recaptcha/api/siteverify',
                data = {'secret':'6LevmisUAAAAAAAn7YTyb0g7nQH60-J_9wDyAl0y',
                        'remoteip': self.request.META.get('REMOTE_ADDR', ''),
                        'response': self.request.POST.get('g-recaptcha-response', '')})

        response_payload = json.loads(response.text)

        if not response_payload['success']:
            return redirect('https://www.youtube.com/watch?v=QH2-TGUlwu4')

        if self.request.POST.get('honeypot', ''):
            return redirect('https://www.youtube.com/watch?v=KgbSjRMqyjc')

        return super(ContadorCreateView, self).form_valid(form)

    def get_success_url(self):
        return reverse_lazy('index')

class PasswordResetViewSendgrid(PasswordResetView):
    form_class = PasswordResetFormSendgrid

geral/templates/geral/base.html
<html>
    <head>
        <meta charset="utf-8">
        <title>Sistema da Tesouraria do Garoa</title>

        <style>
        </style>
        {% block extrastyle %}{% endblock %}

        {% block extrascripts %}
        {% endblock %}
    </head>

    <body>
        <div style="width: 100%;">
            <div style="width: 150px; float:left;">
                <img src="https://garoa.net.br/ghc/ghc_logo.png">
            </div>

            <div style="width: 50%; float:left">
                <h1>Sistema da Tesouraria do Garoa</h1>
                <p>Esse sistema serve para que os associados do Garoa se comunicarem oficialmente com a tesouraria.</br> Aqui você pode quitar seus debitos e pedir reembolsos.<p>

                {% block nav-global %}
                <h2>Acesso</h2>
                <ul>
                    {% if not user.is_authenticated %}
                    <li><a href="{% url 'login' %}">Login</a></li>
                    {% else %}
                    <li><a href="{% url 'logout' %}">Logout</a>: {{ user }}</li>
                    {% endif %}
                    <li><a href="{% url 'user-create' %}">Cadastro</a></li>
                    <li><a href="{% url 'lancamento-list' %}">Minha Conta</a></li>
                </ul>
                <h2>Links Instutucionais</h2>
                <ul>
                    <li><a href="https://garoa.net.br/wiki/P%C3%A1gina_principal">Wiki do Garoa</a></li>
                    <li><a href="https://garoa.net.br/wiki/Categoria:Reuni%C3%B5es">Atas do Conselho Manda Chuva</a></li>
                    <li><a href="https://garoa.net.br/wiki/Mensalidades">Mensalidades</a></li>
                </ul>
                {% endblock %}

                {% block content %}
                {% endblock %}

            </div>

            <div style="float:left; width: 25%;">
                {% block doacoes %}
                {% endblock %}
            </div>

            <div style="clear:both"></div>

        </div>
        </div> <!-- ? bug -->

        <div style="clear:both"></div>

        {% block footer %}
        </div>
        <div id="footer" style="width: 100%;">
            <hr>
            <div style="float:left; width: 147px;">
            </div>
            <div style="float:right; width: 89%;">
                <p>Não critique o design desta página. <br> Se você quiser fazer um melhor, você está convidado a mandar um pull-request <a href="https://github.com/garoa/sistema-tesouraria">https://github.com/garoa/sistema-tesouraria</a><p>
            </div>
        </div>
        {% endblock %}

    </body>
</html>

geral/templates/geral/index.html
{% extends "geral/base.html" %}
{% load i18n static %}

{% block doacoes %}
<h2>Faça uma Doação</h2>

<ul>
    <li><a href="https://garoa.net.br/wiki/Contribui%C3%A7%C3%B5es">Como contribuir para o Garoa</a></li>
    <li><a href="https://garoa.net.br/wiki/Como_se_associar">Como se associar</a></li>
</ul>

<h2>Amigos do Garoa</h2>
<p>Você pode fazer uma doação <b>Recorrente</b>:</p>

<div>
    <div>
        <form action="https://www.paypal.com/cgi-bin/webscr" method="post" target="_top">
            <input type="hidden" name="cmd" value="_s-xclick">
            <input type="hidden" name="hosted_button_id" value="CMUNHJYRJUG4A">
            <table>
            <tr><td><input type="hidden" name="on0" value=""></td></tr><tr><td><select name="os0">
                <option value="Amigos do Garoa">Amigos do Garoa : R$30,00 BRL - mensalmente</option>
            </select> </td></tr>
            <tr><td><input type="hidden" name="on1" value="Observação:">Observação:</td></tr><tr><td><input type="text" name="os1" maxlength="200"></td></tr>
            </table>
            <input type="hidden" name="currency_code" value="BRL">
            <input type="image" src="https://www.paypalobjects.com/pt_BR/i/btn/btn_subscribe_SM.gif" border="0" name="submit" alt="PayPal - A maneira fácil e segura de enviar pagamentos online!">
            <img alt="" border="0" src="https://www.paypalobjects.com/pt_BR/i/scr/pixel.gif" width="1" height="1">
        </form>
    </div>


    <div>
        <!-- INICIO FORMULARIO BOTAO PAGSEGURO: NAO EDITE OS COMANDOS DAS LINHAS ABAIXO
        <form action="https://pagseguro.uol.com.br/pre-approvals/request.html" method="post">
        <input type="hidden" name="code" value="AC0C517FA9A934855416DFAF43C62B56" />
        <input type="hidden" name="iot" value="button" />
        <input type="image" src="https://stc.pagseguro.uol.com.br/public/img/botoes/assinaturas/120x53-assinar-roxo.gif" name="submit" alt="Pague com PagSeguro - É rápido, grátis e seguro!" width="120" height="53" />
        </form>
        FINAL FORMULARIO BOTAO PAGSEGURO -->
    </div>

    <div style="clear: both;"></div>
</div>

<h2>Doe</h2>
<p>Você pode fazer uma doação online:</p>

<div>
    <div style="float: left; width: 220px;">
        <img src="https://www.paypalobjects.com/webstatic/en_US/i/buttons/PP_logo_h_200x51.png" alt="PayPal Logo">
    </div>
    <div>
        <form action="https://www.paypal.com/cgi-bin/webscr" method="post" target="_top">
        <input type="hidden" name="cmd" value="_s-xclick">
        <input type="hidden" name="hosted_button_id" value="HGTMYD9HW7YWW">
        <input type="image" src="https://www.paypalobjects.com/pt_BR/BR/i/btn/btn_donateCC_LG.gif" border="0" name="submit" alt="PayPal - A maneira fácil e segura de enviar pagamentos online!">
        <img alt="" border="0" src="https://www.paypalobjects.com/pt_BR/i/scr/pixel.gif" width="1" height="1">
        </form>
    </div>
    <div style="clear: both;"></div>
</div>

<div>
    <div>
        <img src="https://en.bitcoin.it/w/images/en/e/ed/Bitcoin_accepted_here_printable.png" height="70" width="183" alt="Bitcoin accepted here!">
    </div>
    <div>
        <p>1GHCmeB21BTVQ1W4YwrwrvrgXLjrWiTewP</p>
    <div>
    <div style="clear: both;"></div>
</div>

<div>
    <div style="float: left; width: 100px;">
        <a href="https://unlock.fund/pt-BR/garoa" rel="nofollow"><img alt="Logo-unlock.png" src="" srcset="https://garoa.net.br/w/images/thumb/Logo-unlock.png/150px-Logo-unlock.png" height="43" width="100"></a>
    </div>
    <div>
        <a href="https://unlock.fund/pt-BR/garoa" rel="nofollow"><img alt="Qr unlock garoa.png" src="https://garoa.net.br/w/images/Qr_unlock_garoa.png" height="200" width="200"></a>
    </div>
    <div style="clear: both;"></div>
</div>
{% endblock %}

geral/templates/geral/lancamento_form.html
{% extends "geral/base.html" %}
{% load i18n static %}

{% block extrascripts %}
      <link rel="stylesheet" href="//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">
      <link rel="stylesheet" href="/resources/demos/style.css">
      <script src="https://code.jquery.com/jquery-1.12.4.js"></script>
      <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>

      <script>
          $( function() {
              $( "#id_timestamp_comprovante" ).datepicker();
            } );
      </script>

{% endblock %}

    {% block nav-global %}
    <h2>Acesso</h2>
    <ul>
        <li><a href="{% url 'logout' %}">Logout</a>: {{ request.user }}</li>
        <li><a href="{% url 'lancamento-list' %}">Minha Conta</a></li>
        <li><a href="{% url 'plano-list' %}">Meus Planos</a></li>
        <li>Submeter Comprovante</li>
    </ul>
    {% endblock%}

    {% block content %}
    <h2>Submissão de comprovantes:</h2>
    <form enctype="multipart/form-data" method="post" action="">{% csrf_token %}
        <table>
            {{ form.as_table }}
        </table>
        <input type="submit" value="Save" />
    </form>
    <p>
    Todo lançamento sofre analise da Tesouraria.<br>
    Enquanto o lançamento não for aprovado, ele aparece no saldo como 'Pending'.<br>
    Em caso de dúvidas, entre em contato: tesoureiro@garoa.net.br
    </p>
    {% endblock %}

geral/templates/geral/lancamento_list.html
{% extends "geral/base.html" %}
{% load i18n static %}
    {% block nav-global %}
    <h2>Acesso</h2>
    <ul>
        <li><a href="{% url 'logout' %}">Logout</a>: {{ request.user }}</li>
        <li>Minha Conta</li>
        <li><a href="{% url 'plano-list' %}">Meus Planos</a></li>
        <li><a href="{% url 'lancamento-create'%}">Submeter Comprovante</a></li>
    </ul>
    {% endblock%}

    {% block content %}

    <h2>Pagamento pelo Paypal: <h2>
    <div>
        <div>

<form action="https://www.paypal.com/cgi-bin/webscr" method="post" target="_top">
<input type="hidden" name="cmd" value="_s-xclick">
<input type="hidden" name="hosted_button_id" value="SFWHVQ9KY2KJL">
<table>
<tr><td><input type="hidden" name="on0" value=""></td></tr><tr><td><select name="os0">
    <option value="associado do Garoa">associado do Garoa : R$95,00 BRL - mensalmente</option>
</select> </td></tr>
</table>
<input type="hidden" name="currency_code" value="BRL">
<input type="image" src="https://www.paypalobjects.com/pt_BR/BR/i/btn/btn_subscribeCC_LG.gif" border="0" name="submit" alt="PayPal - A maneira fácil e segura de enviar pagamentos online!">
<img alt="" border="0" src="https://www.paypalobjects.com/pt_BR/i/scr/pixel.gif" width="1" height="1">
</form>

        </div>
        <div style="clear: both;"></div>
    </div>

    <h2>Plano:</h2>
        {% if user.associado.get_plano_vigente %}
            Atualmente você está cadastrado nos seguintes planos:
            <ul>
                {% with  user.associado.get_plano_vigente as p %}
                {% if p.state == "p" %}<li><font color="gray">{{ p }}</font></li>{% endif %}
                {% if p.state == "v" %}<li>{{ p }}</li>{% endif %}
                {% if p.state == "e" %}<li><strike>{{ p }}</strike></li>{% endif %}
                {% endwith %}
            </ul>
        {% else %}
            <font color="red">Por favor, cadastre ou atualize seu plano.</font>
            > <a href="{% url 'plano-list' %}">Meus Planos</a>
            <br>* Se sistema não encontrar um plano cadastrado, ele irá debitar mensalmente a mensalidade padrão
        {% endif %}

    <h2>Saldo:</h2>
    <table border=1>
        <tr>
            <th>ID</th>
            <th>Timestamp</th>
            <th>Fonte</th>
            <th>Status</th>
            <th>Valor</th>
            <th>C/D</th>
            <th>Descrição</th>
            <th>Saldo</th>
        </tr>
        {% for reg in object_list %}
            <tr>
                <td>{{ reg.id }}</td>
                <td>{{ reg.approved_timestamp|default:"_ *¹" }}</td>
                <td>{{ reg.get_autor_display }}</td>
                <td>{{ reg.get_moderation_status_display }}</td>
                <td>{{ reg.valor }}</td>
                <td>{{ reg.credito_debito }}</td>
                <td>{{ reg.descricao }}</td>
                <td>R$ {{ reg.saldo }}</td>
            </tr>
        {% endfor %}
    </table>

    <p>Em caso de dúvidas, entre em contato: tesoureiro@garoa.net.br <br> *¹ - Transções sujeitas a aprovação
    </p>


    {% endblock %}

geral/templates/geral/plano_form.html
{% extends "geral/base.html" %}
{% load i18n static %}

{% block extrascripts %}
      <link rel="stylesheet" href="//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">
      <link rel="stylesheet" href="/resources/demos/style.css">
      <script src="https://code.jquery.com/jquery-1.12.4.js"></script>
      <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
{% endblock %}

    {% block nav-global %}
    <h2>Acesso</h2>
    <ul>
        <li><a href="{% url 'logout' %}">Logout</a>: {{ request.user }}</li>
        <li><a href="{% url 'lancamento-list' %}">Minha Conta</a></li>
        <li><a href="{% url 'plano-list' %}">Meus Planos</a></li>
        <li>Incluir Plano</li>
    </ul>
    {% endblock%}

    {% block content %}
    <h2>Inclusão de Planos:</h2>
    <form method="post" action="" >{% csrf_token %}
        <table>
            {{ form.as_table }}
        </table>
        <input type="submit" value="Save" />
    </form>
    <p>
    Todo plano sofre analise da Tesouraria.<br>
    Enquanto o lançamento não for aprovado, ele aparece no saldo como 'Pending'.<br>
    Em caso de dúvidas, entre em contato: tesoureiro@garoa.net.br
    </p>
    {% endblock %}

geral/templates/geral/plano_list.html
{% extends "geral/base.html" %}
{% load i18n static %}
    {% block nav-global %}
    <h2>Acesso</h2>
    <ul>
        <li><a href="{% url 'logout' %}">Logout</a>: {{ request.user }}</li>
        <li><a href="{% url 'lancamento-list' %}">Minha Conta</a></li>
        <li>Meus Planos</li>
        <li><a href="{% url 'plano-create' %}">Incluir Plano</a></li>
    </ul>
    {% endblock%}

    {% block content %}
    <h2>Planos:</h2>
    <table border=1>
        <tr>
            <!-- <th>ID</th> -->
            <!-- <th>Timestamp</th> -->
            <th>Status</th>
            <th>Plano</th>
            <th>Valor</th>
            <th>Descrição</th>
            <th>Inicio</th>
            <th>Validade</th>
        </tr>
        {% for reg in object_list %}
            <tr>
                <!-- <td>{{ reg.id }}</td> -->
                <!-- <td>{{ reg.approved_timestamp|default:"_ *¹" }}</td> -->
                <td>{{ reg.get_moderation_status_display }}</td>
                <td>{{ reg.get_plano_display }}</td>
                <td>R$ {{ reg.valor }}</td>
                <td>{{ reg.descricao }}</td>
                <td>{{ reg.validade_data_inicio }}</td>
                <td>{{ reg.data_validade_fim|default:"_ *²" }}</td>
            </tr>
        {% endfor %}

    </table>

    <p>Em caso de dúvidas, entre em contato: tesoureiroa at garoa.net.br <br>
    *¹ - Transções sujeitas a aprovação<br>
    *² - Planos mensais tem validade indeterminada.<br>
    </p>

    <p> Todo associado é cadastrado no sistema no "Plano Padrão".<br>
    O associado pode optar por outro plano a qualquer momento.<br>
    Durante o mês de Fevereiro o associado pode optar pelo plano Anual com desconto.<br>
    Existem também o programa Starving Hacker que proteje o associado que passa por dificultades financeiras.<br>
    </p>
    {% endblock %}